version: 0.2

env:
  secrets-manager:
    # key: secret-id:json-key:version-stage:version-id
    # GITHUB_TOKEN: secret-id:json-key:version-stage:version-id
    # GITHUB_TOKEN: arn:aws:secretsmanager:eu-west-1:175545130244:secret:shared/github/token/brainly-integration-MJ5Fod
    GITHUB_TOKEN: arn:aws:secretsmanager:eu-central-1:481992040149:secret:github-token-rQ7RYS

phases:
  pre_build: # get test-runer repo
    on-failure: ABORT
    commands:
      - git clone https://oauth2:$GITHUB_TOKEN@github.com/gzbd/aws-codebuild-test-runner.git
  build: #  build local image of the app, and override the image in docker-compose, run tests
    on-failure: ABORT
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - cat main.go
      - docker build -t aws-codebuild-test-service .
      - cd aws-codebuild-test-runner
      - source ./default_env_vars
      - docker-compose run integration_tests
      - docker-compose down
